import "./globals.css";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/logoTab.svg" />
      </head>
      <body className="bg-stone-200 text-gray-900 ltr:!font-poppins rtl:!font-cairo dark:bg-gray-900 dark:text-slate-100">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};
export default RootLayout;
